### ISSUE TITLE
Serial Read/Serial Print

### ISSUE THREAD

**Issue by mininuke69** [mininuke69/PetScanner#4]
Serial.print(ss.read()) gives a string with 5156484849485152515152505313

**Comment by mininuke69** [comment]
`Serial.print(ss.read());` gives 5156484849485152515152505313
`Serial.write(ss.read());` gives 3800103433425
`Serial.print(ss.readString());` gives 3800103433425

**Comment by CBVRT2008** [comment]
ss.readString(); werkt ook met de SD library, deze geeft dan de inhoud in aparte regels. Bijvoorbeeld:

14:31:46.409 -> string
14:31:46.409 -> string
14:31:46.409 -> string
14:31:46.446 -> string
14:31:46.446 -> string
14:31:46.446 -> string
14:31:46.446 -> string
14:31:46.491 -> string
14:31:46.491 -> string
14:31:46.491 -> string
14:31:46.491 -> string
14:31:46.491 -> string
